export interface Properties {
  /**
   * userId to pass to API as parameter
   */
  userId?: string;
  /**
   * the API Key generated by the Joystick backend. The only required property.
   */
  apiKey: string;
  semVer?: string;
  params?: Record<string, unknown>;
  options?: {
    cacheExpirationSeconds?: number;
    serialized?: boolean;
  };
}
