name: Publish Package to npmjs

on:
  release:
    types: [published]

jobs:
  test:
    strategy:
      matrix:
        version: [16, 18, 19]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "${{ matrix.version }}"

      - name: Install dependencies
        run: npm ci

      - name: Run eslint and prettier check
        run: npm run lint

      - name: Run tests
        run: npm test

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - name: Git configuration
        run: |
          git config --global user.email "code@getjoystick.com"
          git config --global user.name "GitHub Actions"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
