name: Release package

on:
  workflow_dispatch:

jobs:
  release:
    strategy:
      matrix:
        version: [ 16,18,19 ]
        os: [ ubuntu-latest, windows-latest, mac-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '${{ matrix.version }}'

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm test
