name: Testing package
on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Release type (one of): patch, minor, major, prepatch, preminor, premajor, prerelease'
        required: true

jobs:
  build:
    #    strategy:
    #      matrix:
    #        version: [10,12,14,16]
    #        os: [ubuntu-latest,macos-latest,windows-latest]
    #    runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          #          node-version: ${{ matrix.version }}
          node-version: '16'
      - run: npm ci
      - run: npm test
